# Generated by Django 3.2.9 on 2021-12-09 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_from_api',
        ),
        migrations.RemoveField(
            model_name='story',
            name='is_from_api',
        ),
    ]
